
export const WOMENSFASHION_PRODUCTS_REQUEST = 'WOMENSFASHION_PRODUCTS_REQUEST';
export const WOMENSFASHION_PRODUCTS_SUCCESS = 'WOMENSFASHION_PRODUCTS_SUCCESS';
export const WOMENSFASHION_PRODUCTS_FAIL = 'WOMENSFASHION_PRODUCTS_FAIL';
export const WOMENSFASHION_SINGLE_PRODUCT = 'WOMENSFASHION_SINGLE_PRODUCT';
export const WOMENSFASHION_PRODUCT_DELETE = 'WOMENSFASHION_PRODUCT_DELETE';
export const WOMENSFASHION_SINGLE_PRODUCT_PAGE = 'WOMENSFASHION_SINGLE_PRODUCT_PAGE';
