
export const ELECTRONIC_REQUEST = "ELECTRONIC_REQUEST";
export const ELECTRONIC_SUCCESS = "ELECTRONIC_SUCCESS";
export const ELECTRONIC_FAIL = "ELECTRONIC_FAIL";
export const ELECTRONIC_DELETE = "ELECTRONIC_DELETE";
export const SINGLE_ELECTRONIC = "SINGLE_ELECTRONIC";