export const BEAUTY_PRODUCT_REQUEST = "BEAUTY_PRODUCT_REQUEST";
export const BEAUTY_PRODUCT_SUCCESS = "BEAUTY_PRODUCT_SUCCESS";
export const BEAUTY_PRODUCT_FAIL = "BEAUTY_PRODUCT_FAIL";
export const BEAUTY_PRODUCT_DELETE = "BEAUTY_PRODUCT_DELETE";
export const BEAUTY_PRODUCT_SINGLE = "BEAUTY_PRODUCT_SINGLE";