
export const MANS_FASHION_REQUEST = "MANS_FASHION_REQUEST";
export const MANS_FASHION_SUCCESS = "MANS_FASHION_SUCCESS";
export const MANS_FASHION_FAIL = "MANS_FASHION_FAIL";
export const MANS_FASHION_DELETE = "MANS_FASHION_DELETE";
export const MANS_FASHION_SINGLE = "MANS_FASHION_SINGLE";