export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL= 'PRODUCT_FAIL';
export const SINGLE_PRODUCT = 'SINGLE_PRODUCT';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const SINGLE_PRODUCT_PAGE = 'SINGLE_PRODUCT_PAGE';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
